version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - posthog-network
    depends_on:
      - posthog
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/manifest', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Caddy reverse proxy for MCP server
  caddy-mcp:
    image: caddy:2-alpine
    container_name: caddy-mcp
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - posthog-network
    depends_on:
      - mcp-server

networks:
  posthog-network:
    external: true
    name: posthog_default  # Adjust this to match your PostHog network name
